# Generated by Django 3.1.3 on 2020-11-29 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myuser', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('tags', models.ManyToManyField(to='tag.Tag', verbose_name='태그')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myuser.myuser', verbose_name='작성자')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글',
                'db_table': 'my_board',
            },
        ),
    ]
